apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http-server
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: iperf-server
  selector:
    name: web
